module.exports = {
  // eslint-disable-next-line no-unused-vars
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('books', [
      {
        title: 'A Brief History of Time',
        author: 'Stephen Hawking',
        Genre: 'Non Fiction',
        year: 1988,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Harry Potter and the Philosopher's Stone'",
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 1997,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harry Potter and the Chamber of Secrets',
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 1998,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harry Potter and the Prisoner of Azkaban',
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 1999,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harry Potter and the Goblet of Fire',
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harry Potter and the Order of the Phoenix',
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 2003,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Harry Potter and the Half-Blood Prince',
        author: 'JK Rowling',
        Genre: 'Fantasy',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Avatar: The last Airbender - The Rise of Kyoshi',
        author: 'F.C. Yee',
        Genre: 'Fantasy',
        year: 2019,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Norwegian Wood',
        author: 'Haruki Murakami',
        Genre: 'Fiction',
        year: 1987,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Naomi',
        author: 'Junichiro Tanizaki',
        Genre: 'Fiction',
        year: 1924,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Freakonomics',
        author: 'Steven D. Levitt',
        Genre: 'Non Fiction',
        year: 2005,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Batman: The Killing Joke',
        author: 'Alan Moore',
        Genre: 'Comics',
        year: 1988,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Our Revolution',
        author: 'Bernie Sanders',
        Genre: 'Political',
        year: 2016,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Kitchen Confidential',
        author: 'Anthony Bourdain',
        Genre: 'Non Fiction',
        year: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Coraline',
        author: 'Neil Gaiman',
        Genre: 'Fantasy',
        year: 2002,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'American Gods',
        author: 'Neil Gaiman',
        Genre: 'Fantasy',
        year: 2001,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lord of the Rings: The Fellowship of the Ring',
        author: 'J.R.R Tolkien',
        Genre: 'Fantasy',
        year: 1954,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lord of the Rings: The Two Towers',
        author: 'J.R.R Tolkien',
        Genre: 'Fantasy',
        year: 1954,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Lord of the Rings: The Return of the King',
        author: 'J.R.R Tolkien',
        Genre: 'Fantasy',
        year: 1955,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  // eslint-disable-next-line no-unused-vars
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('books', null, {});
  },
};
